In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [10]:
df = pd.read_csv(r"C:\Users\paraj\pythonbasic\iris.csv")

In [5]:
n1=np.array([10,20,30,40])
n1

array([10, 20, 30, 40])

In [6]:
type(n1)

numpy.ndarray

In [11]:
n2=np.array([[10,20,30,40,50],[10,20,40,60,70],[10,20,40,60,70],[30,90,70,60,70]])
n2

array([[10, 20, 30, 40, 50],
       [10, 20, 40, 60, 70],
       [10, 20, 40, 60, 70],
       [30, 90, 70, 60, 70]])

In [12]:
n3=np.zeros((4,5))
n3

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
n4=np.full((3,3),9)
n4

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

In [18]:
n5=np.arange(10,20)
n5

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [19]:
n6=np.arange(1,20,3)
n6

array([ 1,  4,  7, 10, 13, 16, 19])

In [20]:
n7=np.random.randint(100,1000,10)
n7

array([849, 785, 909, 669, 108, 113, 345, 572, 244, 383])

In [21]:
n8=np.random.randint(100000,999999,1)
n8

array([844486])